// src/config/fieldLabels.js

const fieldLabels = {
    bankAccountNumber: "Номер банковского счета",
    conclusionDate: "Дата заключения",
    conclusionReason: "Причина заключения",
    contractNumber: "Номер договора",
    cost: "Стоимость",
    durationEndDate: "Дата окончания действия",
    durationStartDate: "Дата начала действия",
    eisContractUrl: "Ссылка на договор ЕИС",
    eisId223: "EIS ID 223",
    executionEndDate: "Дата окончания исполнения",
    executionStartDate: "Дата начала исполнения",
    id: "ID",
    ikz: "ИКЗ",
    is2020: "2020",
    is223: "223",
    kpgz: "КПГЗ",
    lotIkz: "ИКЗ лота",
    lotProtocolDate: "Дата протокола лота",
    lotProtocolNumber: "Номер протокола лота",
    lotProtocolTypeName: "Тип протокола лота",
    lotTenderRegistryNumberOos: "Регистрационный номер тендера лота",
    lotTenderTenderIkz: "ИКЗ тендера лота",
    name: "Наименование",
    okpd2: "ОКПД2",
    registryDate: "Дата регистрации",
    registryNumber: "Регистрационный номер",
    registryNumberOos: "Регистрационный номер ООС",
    singleVendorPurchaseAggregatePurchase: "Агрегированная закупка",
    singleVendorPurchaseCode: "Код закупки",
    singleVendorPurchaseName: "Наименование закупки",
    spgz: "СПГЗ",
    state_Name: "Статус",
    supplier_Inn: "ИНН поставщика",
    supplier_Kpp: "КПП поставщика",
    supplier_Name: "Поставщик",
};

export default fieldLabels;